In [1]:
import pandas as pd
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
import pickle
import graphviz 
import warnings
from sklearn.model_selection import KFold

warnings.filterwarnings('ignore')

In [2]:
# loading dataset iris
from sklearn import datasets
iris = datasets.load_iris()

# data training
X = iris.data

# target
y = iris.target

In [3]:
import pandas as pd

play = pd.read_csv("weather.nominal.csv")
print(play);

     outlook temperature humidity  windy play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no


In [4]:
# kNN full-training
kNN = KNeighborsClassifier(n_neighbors=3)
kNN.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [5]:
# save model to external file .pkl
import pickle
kNN_file = open('kNN_full-training.pkl', 'wb')
pickle.dump(kNN, kNN_file)
kNN_file.close()

In [6]:
# Naive Bayes full-training
NB = GaussianNB()
NB.fit(X,y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [7]:
# save model to external file .pkl
import pickle
NB_file = open('NB_full-training.pkl', 'wb')
pickle.dump(NB, NB_file)
NB_file.close()

In [8]:
# Decision Tree full-training
DT = tree.DecisionTreeClassifier()
DT.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [9]:
# save model to external file .pkl
import pickle
DT_file = open('DT_full-training.pkl', 'wb')
pickle.dump(DT, DT_file)
DT_file.close()

In [10]:
# display decision tree from learning
import graphviz 

dot_data = tree.export_graphviz(DT, out_file=None, 
                         feature_names=iris.feature_names,  
                         class_names=iris.target_names,  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = graphviz.Source(dot_data)  
graph.render(filename='tree_full-training',format='png')

'tree_full-training.png'

![Decision Tree with Full-Training](tree_full-training.png)

In [11]:
# Neural Network Multilayer Perceptron full-training
MLP = MLPClassifier()
MLP.fit(X,y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [12]:
# save model to external file .pkl
import pickle
MLP_file = open('MLP_full-training.pkl', 'wb')
pickle.dump(MLP, MLP_file)
MLP_file.close()

In [13]:
# split dataset 90% training and 10% testing
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [14]:
# kNN 90%-training
# training data
kNN2 = KNeighborsClassifier(n_neighbors=3)
kNN2.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [15]:
# kNN 90%-training
# predict dataset testing with training model
from sklearn.metrics import confusion_matrix

kNN2_y_predict = kNN2.predict(X_test)

# kNN 90%-training
# display performance and confusion matrix
print('Dataset iris 90% training with kNN')

print('\nAttributes:\n', iris.target_names)
print('\nAccuracy: \n', accuracy_score(y_test, kNN2_y_predict))
print('\nPresicion: \n', precision_score(y_test, kNN2_y_predict, average=None))
print('\nRecall: \n', recall_score(y_test, kNN2_y_predict, average=None))
print('\nConfusion Matrix [True→ Predict↓]\n', confusion_matrix(y_test, kNN2_y_predict))

Dataset iris 90% training with kNN

Attributes:
 ['setosa' 'versicolor' 'virginica']

Accuracy: 
 0.9333333333333333

Presicion: 
 [1.  1.  0.5]

Recall: 
 [1.  0.8 1. ]

Confusion Matrix [True→ Predict↓]
 [[9 0 0]
 [0 4 1]
 [0 0 1]]


In [16]:
# Naive Bayes 90%-training
# training data
NB2 = GaussianNB()
NB2.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [17]:
# Naive Bayes 90%-training
# predict dataset testing with training model
NB2_y_predict = NB2.predict(X_test)

# display performance and confusion matrix
print('Dataset iris 90% training with Naive Bayes')

print('\nAttributes:\n', iris.target_names)
print('\nAccuracy: \n', accuracy_score(y_test, NB2_y_predict))
print('\nPresicion: \n', precision_score(y_test, NB2_y_predict, average=None))
print('\nRecall: \n', recall_score(y_test, NB2_y_predict, average=None))
print('\nConfusion Matrix [True→ Predict↓]\n', confusion_matrix(y_test, NB2_y_predict))

Dataset iris 90% training with Naive Bayes

Attributes:
 ['setosa' 'versicolor' 'virginica']

Accuracy: 
 0.8666666666666667

Presicion: 
 [1.  0.8 0. ]

Recall: 
 [1.  0.8 0. ]

Confusion Matrix [True→ Predict↓]
 [[9 0 0]
 [0 4 1]
 [0 1 0]]


In [18]:
# Decision Tree 90%-training
# training data
DT2 = tree.DecisionTreeClassifier()
DT2.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [19]:
# Decision Tree 90%-training
# predict dataset testing with training model
DT2_y_predict = DT2.predict(X_test)

# display performance and confusion matrix
print('Dataset iris 90% training with Desicion Tree')

print('\nAttributes:\n', iris.target_names)
print('\nAccuracy: \n', accuracy_score(y_test, DT2_y_predict))
print('\nPresicion: \n', precision_score(y_test, DT2_y_predict, average=None))
print('\nRecall: \n', recall_score(y_test, DT2_y_predict, average=None))
print('\nConfusion Matrix [True→ Predict↓]\n', confusion_matrix(y_test, DT2_y_predict))

Dataset iris 90% training with Desicion Tree

Attributes:
 ['setosa' 'versicolor' 'virginica']

Accuracy: 
 0.9333333333333333

Presicion: 
 [1.  1.  0.5]

Recall: 
 [1.  0.8 1. ]

Confusion Matrix [True→ Predict↓]
 [[9 0 0]
 [0 4 1]
 [0 0 1]]


In [20]:
# Neural Network Multilayer Perceptron 90%-training
# training data
MLP2 = MLPClassifier()
MLP2.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [21]:
# Neural Network Multilayer Perceptron 90%-training
# predict dataset testing with training model
MLP2_y_predict = MLP2.predict(X_test)

# display performance and confusion matrix
print('Dataset iris 90% training with Neural Network Multilayer Perceptron')

print('\nAttributes:\n', iris.target_names)
print('\nAccuracy: \n', accuracy_score(y_test, MLP2_y_predict))
print('\nPresicion: \n', precision_score(y_test, MLP2_y_predict, average=None))
print('\nRecall: \n', recall_score(y_test, MLP2_y_predict, average=None))
print('\nConfusion Matrix [True→ Predict↓]\n', confusion_matrix(y_test, MLP2_y_predict))

Dataset iris 90% training with Neural Network Multilayer Perceptron

Attributes:
 ['setosa' 'versicolor' 'virginica']

Accuracy: 
 0.8666666666666667

Presicion: 
 [1.         1.         0.33333333]

Recall: 
 [1.  0.6 1. ]

Confusion Matrix [True→ Predict↓]
 [[9 0 0]
 [0 3 2]
 [0 0 1]]


In [22]:
# save model to external file .pkl
import pickle
kNN2_file = open('kNN_split-90training.pkl', 'wb')
pickle.dump(kNN2, kNN2_file)
kNN2_file.close()

NB2_file = open('NB_split-90training.pkl', 'wb')
pickle.dump(NB2, NB2_file)
NB2_file.close()

DT2_file = open('DT_split-90training.pkl', 'wb')
pickle.dump(DT2, DT2_file)
DT2_file.close()

MLP2_file = open('MLP_split-90training.pkl', 'wb')
pickle.dump(MLP2, MLP2_file)
MLP2_file.close()

In [23]:
#10-Fold Cross Validation
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

iris = load_iris()

X = iris.data

y = iris.target

kf = KFold(n_splits=10,shuffle=True)

print('Dataset iris 10-Fold Cross Validation')
print('\nAttributes:\n', iris.target_names)
i=1
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    print('\nIterasi ', i)
    i = i+1
    
    # kNN 10-Fold Cross Validation
    kNN3 = KNeighborsClassifier(n_neighbors=3)
    kNN3.fit(X_train,y_train)
    
    # display performance Decision Tree 10-Fold Cross Validation
    kNN3_y_predict = kNN3.predict(X_test)
    print('kNN : Accuracy:', accuracy_score(y_test, kNN3_y_predict), 'Presicion:', precision_score(y_test, kNN3_y_predict, average=None), 'Recall:', recall_score(y_test, kNN3_y_predict, average=None))
    
    #Naive Bayes 10-Fold Cross Validation
    NB3 = GaussianNB()
    NB3.fit(X_train,y_train)
    
    #display performance Naive Bayes 10-Fold Cross Validation
    NB3_y_predict = NB3.predict(X_test)
    print('NB  : Accuracy:', accuracy_score(y_test, NB3_y_predict), 'Presicion:', precision_score(y_test, NB3_y_predict, average=None), 'Recall:', recall_score(y_test, NB3_y_predict, average=None))
    
    #Decision Tree 10-Fold Cross Validation
    DT3 = tree.DecisionTreeClassifier()
    DT3.fit(X_train,y_train)
    
    #display performance Decision Tree 10-Fold Cross Validation
    DT3_y_predict = DT3.predict(X_test)
    print('DTL : Accuracy:', accuracy_score(y_test, DT3_y_predict), 'Presicion:', precision_score(y_test, DT3_y_predict, average=None), 'Recall:', recall_score(y_test, DT3_y_predict, average=None))
    
    #Neural Network Multilayer Perceptron 10-Fold Cross Validation
    MLP3 = MLPClassifier()
    MLP3.fit(X_train,y_train)
    
    #display performance Neural Network Multilayer Perceptron 10-Fold Cross Validation
    MLP3_y_predict = MLP3.predict(X_test)
    print('DTL : Accuracy:', accuracy_score(y_test, MLP3_y_predict), 'Presicion:', precision_score(y_test, MLP3_y_predict, average=None), 'Recall:', recall_score(y_test, MLP3_y_predict, average=None))
    

Dataset iris 10-Fold Cross Validation

Attributes:
 ['setosa' 'versicolor' 'virginica']

Iterasi  1
kNN : Accuracy: 0.9333333333333333 Presicion: [1.         1.         0.85714286] Recall: [1.   0.75 1.  ]
NB  : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]
DTL : Accuracy: 0.8666666666666667 Presicion: [1.         0.75       0.83333333] Recall: [1.         0.75       0.83333333]
DTL : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]

Iterasi  2
kNN : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]
NB  : Accuracy: 0.9333333333333333 Presicion: [1.         0.83333333 1.        ] Recall: [1.   1.   0.75]
DTL : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]
DTL : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]

Iterasi  3
kNN : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]
NB  : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]
DTL : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1. 1. 1.]
DTL : Accuracy: 1.0 Presicion: [1. 1. 1.] Recall: [1

In [24]:
import numpy as np

# create new instance
X_new = np.array([[7.1, 4.5, 6.0, 2.5]])

In [25]:
import pickle

#classification of new instance
file = open('kNN_full-training.pkl', 'rb')
kNN = pickle.load(file)
file.close()

#kNN full-training
class_id = kNN.predict(X_new)
print(class_id, '=', iris.target_names[class_id])

[2] = ['virginica']


In [26]:
import pickle

#classification of new instance
file = open('NB_full-training.pkl', 'rb')
NB = pickle.load(file)
file.close()

#Naive Bayes full-training
class_id = NB.predict(X_new)
print(class_id, '=', iris.target_names[class_id])

[2] = ['virginica']


In [27]:
import pickle

#classification of new instance
file = open('DT_full-training.pkl', 'rb')
DT = pickle.load(file)
file.close()

#Decision Tree full-training
class_id = DT.predict(X_new)
print(class_id, '=', iris.target_names[class_id])

[2] = ['virginica']


In [28]:
import pickle

#classification of new instance
file = open('MLP_full-training.pkl', 'rb')
MLP = pickle.load(file)
file.close()

#Neural Network Multilayer Perceptron full-training
class_id = MLP.predict(X_new)
print(class_id, '=', iris.target_names[class_id])

[2] = ['virginica']
